#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;
#if defined(__cplusplus)
extern "C" {
#endif

extern void _APCounter2_reg(void);
extern void _CA1ika_reg(void);
extern void _CA1ikdr_reg(void);
extern void _CA1ina_reg(void);
extern void _Cadynamics_reg(void);
extern void _DynamicNetStim_reg(void);
extern void _HH2_reg(void);
extern void _HH_traub_reg(void);
extern void _IC_reg(void);
extern void _ICal_reg(void);
extern void _IKM_reg(void);
extern void _IKsin_reg(void);
extern void _IL_reg(void);
extern void _IL_gutnick_reg(void);
extern void _IM_cortex_reg(void);
extern void _IT_reg(void);
extern void _IT2_reg(void);
extern void _Iahp_reg(void);
extern void _Ican_reg(void);
extern void _MyExp2SynAlpha_reg(void);
extern void _MyExp2SynBB_reg(void);
extern void _MyExp2SynNMDABB_reg(void);
extern void _Nca_reg(void);
extern void _ar_traub_reg(void);
extern void _beforestep_py_reg(void);
extern void _cad_reg(void);
extern void _cadad_reg(void);
extern void _cadecay_destexhe_reg(void);
extern void _cadyn_reg(void);
extern void _cagk_reg(void);
extern void _cal_mh_reg(void);
extern void _cal_mig_reg(void);
extern void _can_mig_reg(void);
extern void _cancr_reg(void);
extern void _canin_reg(void);
extern void _caolmw_reg(void);
extern void _capr_reg(void);
extern void _cat_mig_reg(void);
extern void _cat_traub_reg(void);
extern void _catcb_reg(void);
extern void _ch_CavL_reg(void);
extern void _ch_CavN_reg(void);
extern void _ch_KCaS_reg(void);
extern void _ch_Kdrfastngf_reg(void);
extern void _ch_KvAngf_reg(void);
extern void _ch_KvCaB_reg(void);
extern void _ch_Navngf_reg(void);
extern void _ch_leak_reg(void);
extern void _cp_reg(void);
extern void _cp2_reg(void);
extern void _gabab_reg(void);
extern void _h_BS_reg(void);
extern void _h_harnett_reg(void);
extern void _h_kole_reg(void);
extern void _h_migliore_reg(void);
extern void _hin_reg(void);
extern void _htc_reg(void);
extern void _ican_sidi_reg(void);
extern void _icaolmw_reg(void);
extern void _icapr_reg(void);
extern void _iccr_reg(void);
extern void _iconc_Ca_reg(void);
extern void _iholmkop_reg(void);
extern void _iholmw_reg(void);
extern void _ihpyrkop_reg(void);
extern void _ikscr_reg(void);
extern void _ipulse3_reg(void);
extern void _kBK_reg(void);
extern void _kahppr_reg(void);
extern void _kaolmkop_reg(void);
extern void _kap_BS_reg(void);
extern void _kapcb_reg(void);
extern void _kapin_reg(void);
extern void _kapyrkop_reg(void);
extern void _kca_reg(void);
extern void _kcaolmw_reg(void);
extern void _kcpr_reg(void);
extern void _kctin_reg(void);
extern void _kdmc_BS_reg(void);
extern void _kdr2_orig_reg(void);
extern void _kdr_BS_reg(void);
extern void _kdrbwb_reg(void);
extern void _kdrcr_reg(void);
extern void _kdrin_reg(void);
extern void _kdrolmkop_reg(void);
extern void _kdrpr_reg(void);
extern void _kdrpyrkop_reg(void);
extern void _kl_reg(void);
extern void _km_reg(void);
extern void _kv_reg(void);
extern void _my_exp2syn_reg(void);
extern void _na_2_reg(void);
extern void _naf2_reg(void);
extern void _nafbwb_reg(void);
extern void _nafcr_reg(void);
extern void _nafolmkop_reg(void);
extern void _nafpr_reg(void);
extern void _nafpyrkop_reg(void);
extern void _nafx_reg(void);
extern void _nap_sidi_reg(void);
extern void _nax_BS_reg(void);
extern void _naz_reg(void);
extern void _ntIh_reg(void);
extern void _ntleak_reg(void);
extern void _ntt_reg(void);
extern void _ntt_int_reg(void);
extern void _pasi_reg(void);
extern void _savedist_reg(void);
extern void _tia_reg(void);
extern void _vecstim_reg(void);
extern void _wrap_reg(void);

void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"mod/APCounter2.mod\"");
    fprintf(stderr, " \"mod/CA1ika.mod\"");
    fprintf(stderr, " \"mod/CA1ikdr.mod\"");
    fprintf(stderr, " \"mod/CA1ina.mod\"");
    fprintf(stderr, " \"mod/Cadynamics.mod\"");
    fprintf(stderr, " \"mod/DynamicNetStim.mod\"");
    fprintf(stderr, " \"mod/HH2.mod\"");
    fprintf(stderr, " \"mod/HH_traub.mod\"");
    fprintf(stderr, " \"mod/IC.mod\"");
    fprintf(stderr, " \"mod/ICal.mod\"");
    fprintf(stderr, " \"mod/IKM.mod\"");
    fprintf(stderr, " \"mod/IKsin.mod\"");
    fprintf(stderr, " \"mod/IL.mod\"");
    fprintf(stderr, " \"mod/IL_gutnick.mod\"");
    fprintf(stderr, " \"mod/IM_cortex.mod\"");
    fprintf(stderr, " \"mod/IT.mod\"");
    fprintf(stderr, " \"mod/IT2.mod\"");
    fprintf(stderr, " \"mod/Iahp.mod\"");
    fprintf(stderr, " \"mod/Ican.mod\"");
    fprintf(stderr, " \"mod/MyExp2SynAlpha.mod\"");
    fprintf(stderr, " \"mod/MyExp2SynBB.mod\"");
    fprintf(stderr, " \"mod/MyExp2SynNMDABB.mod\"");
    fprintf(stderr, " \"mod/Nca.mod\"");
    fprintf(stderr, " \"mod/ar_traub.mod\"");
    fprintf(stderr, " \"mod/beforestep_py.mod\"");
    fprintf(stderr, " \"mod/cad.mod\"");
    fprintf(stderr, " \"mod/cadad.mod\"");
    fprintf(stderr, " \"mod/cadecay_destexhe.mod\"");
    fprintf(stderr, " \"mod/cadyn.mod\"");
    fprintf(stderr, " \"mod/cagk.mod\"");
    fprintf(stderr, " \"mod/cal_mh.mod\"");
    fprintf(stderr, " \"mod/cal_mig.mod\"");
    fprintf(stderr, " \"mod/can_mig.mod\"");
    fprintf(stderr, " \"mod/cancr.mod\"");
    fprintf(stderr, " \"mod/canin.mod\"");
    fprintf(stderr, " \"mod/caolmw.mod\"");
    fprintf(stderr, " \"mod/capr.mod\"");
    fprintf(stderr, " \"mod/cat_mig.mod\"");
    fprintf(stderr, " \"mod/cat_traub.mod\"");
    fprintf(stderr, " \"mod/catcb.mod\"");
    fprintf(stderr, " \"mod/ch_CavL.mod\"");
    fprintf(stderr, " \"mod/ch_CavN.mod\"");
    fprintf(stderr, " \"mod/ch_KCaS.mod\"");
    fprintf(stderr, " \"mod/ch_Kdrfastngf.mod\"");
    fprintf(stderr, " \"mod/ch_KvAngf.mod\"");
    fprintf(stderr, " \"mod/ch_KvCaB.mod\"");
    fprintf(stderr, " \"mod/ch_Navngf.mod\"");
    fprintf(stderr, " \"mod/ch_leak.mod\"");
    fprintf(stderr, " \"mod/cp.mod\"");
    fprintf(stderr, " \"mod/cp2.mod\"");
    fprintf(stderr, " \"mod/gabab.mod\"");
    fprintf(stderr, " \"mod/h_BS.mod\"");
    fprintf(stderr, " \"mod/h_harnett.mod\"");
    fprintf(stderr, " \"mod/h_kole.mod\"");
    fprintf(stderr, " \"mod/h_migliore.mod\"");
    fprintf(stderr, " \"mod/hin.mod\"");
    fprintf(stderr, " \"mod/htc.mod\"");
    fprintf(stderr, " \"mod/ican_sidi.mod\"");
    fprintf(stderr, " \"mod/icaolmw.mod\"");
    fprintf(stderr, " \"mod/icapr.mod\"");
    fprintf(stderr, " \"mod/iccr.mod\"");
    fprintf(stderr, " \"mod/iconc_Ca.mod\"");
    fprintf(stderr, " \"mod/iholmkop.mod\"");
    fprintf(stderr, " \"mod/iholmw.mod\"");
    fprintf(stderr, " \"mod/ihpyrkop.mod\"");
    fprintf(stderr, " \"mod/ikscr.mod\"");
    fprintf(stderr, " \"mod/ipulse3.mod\"");
    fprintf(stderr, " \"mod/kBK.mod\"");
    fprintf(stderr, " \"mod/kahppr.mod\"");
    fprintf(stderr, " \"mod/kaolmkop.mod\"");
    fprintf(stderr, " \"mod/kap_BS.mod\"");
    fprintf(stderr, " \"mod/kapcb.mod\"");
    fprintf(stderr, " \"mod/kapin.mod\"");
    fprintf(stderr, " \"mod/kapyrkop.mod\"");
    fprintf(stderr, " \"mod/kca.mod\"");
    fprintf(stderr, " \"mod/kcaolmw.mod\"");
    fprintf(stderr, " \"mod/kcpr.mod\"");
    fprintf(stderr, " \"mod/kctin.mod\"");
    fprintf(stderr, " \"mod/kdmc_BS.mod\"");
    fprintf(stderr, " \"mod/kdr2_orig.mod\"");
    fprintf(stderr, " \"mod/kdr_BS.mod\"");
    fprintf(stderr, " \"mod/kdrbwb.mod\"");
    fprintf(stderr, " \"mod/kdrcr.mod\"");
    fprintf(stderr, " \"mod/kdrin.mod\"");
    fprintf(stderr, " \"mod/kdrolmkop.mod\"");
    fprintf(stderr, " \"mod/kdrpr.mod\"");
    fprintf(stderr, " \"mod/kdrpyrkop.mod\"");
    fprintf(stderr, " \"mod/kl.mod\"");
    fprintf(stderr, " \"mod/km.mod\"");
    fprintf(stderr, " \"mod/kv.mod\"");
    fprintf(stderr, " \"mod/my_exp2syn.mod\"");
    fprintf(stderr, " \"mod/na_2.mod\"");
    fprintf(stderr, " \"mod/naf2.mod\"");
    fprintf(stderr, " \"mod/nafbwb.mod\"");
    fprintf(stderr, " \"mod/nafcr.mod\"");
    fprintf(stderr, " \"mod/nafolmkop.mod\"");
    fprintf(stderr, " \"mod/nafpr.mod\"");
    fprintf(stderr, " \"mod/nafpyrkop.mod\"");
    fprintf(stderr, " \"mod/nafx.mod\"");
    fprintf(stderr, " \"mod/nap_sidi.mod\"");
    fprintf(stderr, " \"mod/nax_BS.mod\"");
    fprintf(stderr, " \"mod/naz.mod\"");
    fprintf(stderr, " \"mod/ntIh.mod\"");
    fprintf(stderr, " \"mod/ntleak.mod\"");
    fprintf(stderr, " \"mod/ntt.mod\"");
    fprintf(stderr, " \"mod/ntt_int.mod\"");
    fprintf(stderr, " \"mod/pasi.mod\"");
    fprintf(stderr, " \"mod/savedist.mod\"");
    fprintf(stderr, " \"mod/tia.mod\"");
    fprintf(stderr, " \"mod/vecstim.mod\"");
    fprintf(stderr, " \"mod/wrap.mod\"");
    fprintf(stderr, "\n");
  }
  _APCounter2_reg();
  _CA1ika_reg();
  _CA1ikdr_reg();
  _CA1ina_reg();
  _Cadynamics_reg();
  _DynamicNetStim_reg();
  _HH2_reg();
  _HH_traub_reg();
  _IC_reg();
  _ICal_reg();
  _IKM_reg();
  _IKsin_reg();
  _IL_reg();
  _IL_gutnick_reg();
  _IM_cortex_reg();
  _IT_reg();
  _IT2_reg();
  _Iahp_reg();
  _Ican_reg();
  _MyExp2SynAlpha_reg();
  _MyExp2SynBB_reg();
  _MyExp2SynNMDABB_reg();
  _Nca_reg();
  _ar_traub_reg();
  _beforestep_py_reg();
  _cad_reg();
  _cadad_reg();
  _cadecay_destexhe_reg();
  _cadyn_reg();
  _cagk_reg();
  _cal_mh_reg();
  _cal_mig_reg();
  _can_mig_reg();
  _cancr_reg();
  _canin_reg();
  _caolmw_reg();
  _capr_reg();
  _cat_mig_reg();
  _cat_traub_reg();
  _catcb_reg();
  _ch_CavL_reg();
  _ch_CavN_reg();
  _ch_KCaS_reg();
  _ch_Kdrfastngf_reg();
  _ch_KvAngf_reg();
  _ch_KvCaB_reg();
  _ch_Navngf_reg();
  _ch_leak_reg();
  _cp_reg();
  _cp2_reg();
  _gabab_reg();
  _h_BS_reg();
  _h_harnett_reg();
  _h_kole_reg();
  _h_migliore_reg();
  _hin_reg();
  _htc_reg();
  _ican_sidi_reg();
  _icaolmw_reg();
  _icapr_reg();
  _iccr_reg();
  _iconc_Ca_reg();
  _iholmkop_reg();
  _iholmw_reg();
  _ihpyrkop_reg();
  _ikscr_reg();
  _ipulse3_reg();
  _kBK_reg();
  _kahppr_reg();
  _kaolmkop_reg();
  _kap_BS_reg();
  _kapcb_reg();
  _kapin_reg();
  _kapyrkop_reg();
  _kca_reg();
  _kcaolmw_reg();
  _kcpr_reg();
  _kctin_reg();
  _kdmc_BS_reg();
  _kdr2_orig_reg();
  _kdr_BS_reg();
  _kdrbwb_reg();
  _kdrcr_reg();
  _kdrin_reg();
  _kdrolmkop_reg();
  _kdrpr_reg();
  _kdrpyrkop_reg();
  _kl_reg();
  _km_reg();
  _kv_reg();
  _my_exp2syn_reg();
  _na_2_reg();
  _naf2_reg();
  _nafbwb_reg();
  _nafcr_reg();
  _nafolmkop_reg();
  _nafpr_reg();
  _nafpyrkop_reg();
  _nafx_reg();
  _nap_sidi_reg();
  _nax_BS_reg();
  _naz_reg();
  _ntIh_reg();
  _ntleak_reg();
  _ntt_reg();
  _ntt_int_reg();
  _pasi_reg();
  _savedist_reg();
  _tia_reg();
  _vecstim_reg();
  _wrap_reg();
}

#if defined(__cplusplus)
}
#endif
